# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: OtpMigration.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'OtpMigration.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12OtpMigration.proto\"\xd0\x04\n\x10MigrationPayload\x12\x37\n\x0eotp_parameters\x18\x01 \x03(\x0b\x32\x1f.MigrationPayload.OtpParameters\x12\x0f\n\x07version\x18\x02 \x02(\x05\x12\x12\n\nbatch_size\x18\x03 \x01(\x05\x12\x13\n\x0b\x62\x61tch_index\x18\x04 \x01(\x05\x12\x10\n\x08\x62\x61tch_id\x18\x05 \x01(\x05\x1a\xe6\x01\n\rOtpParameters\x12\x0e\n\x06secret\x18\x01 \x02(\x0c\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x0e\n\x06issuer\x18\x03 \x01(\t\x12\x34\n\talgorithm\x18\x04 \x01(\x0e\x32\x1b.MigrationPayload.Algorithm:\x04SHA1\x12\x31\n\x06\x64igits\x18\x05 \x01(\x0e\x32\x1c.MigrationPayload.DigitCount:\x03SIX\x12-\n\x04type\x18\x06 \x01(\x0e\x32\x19.MigrationPayload.OtpType:\x04TOTP\x12\x0f\n\x07\x63ounter\x18\x07 \x01(\x03\"V\n\tAlgorithm\x12\x1e\n\x1a\x41LGORITHM_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04SHA1\x10\x01\x12\n\n\x06SHA256\x10\x02\x12\n\n\x06SHA512\x10\x03\x12\x07\n\x03MD5\x10\x04\"=\n\nDigitCount\x12\x1b\n\x17\x44IGIT_COUNT_UNSPECIFIED\x10\x00\x12\x07\n\x03SIX\x10\x01\x12\t\n\x05\x45IGHT\x10\x02\"7\n\x07OtpType\x12\x18\n\x14OTP_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04HOTP\x10\x01\x12\x08\n\x04TOTP\x10\x02')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'OtpMigration_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MIGRATIONPAYLOAD']._serialized_start=23
  _globals['_MIGRATIONPAYLOAD']._serialized_end=615
  _globals['_MIGRATIONPAYLOAD_OTPPARAMETERS']._serialized_start=177
  _globals['_MIGRATIONPAYLOAD_OTPPARAMETERS']._serialized_end=407
  _globals['_MIGRATIONPAYLOAD_ALGORITHM']._serialized_start=409
  _globals['_MIGRATIONPAYLOAD_ALGORITHM']._serialized_end=495
  _globals['_MIGRATIONPAYLOAD_DIGITCOUNT']._serialized_start=497
  _globals['_MIGRATIONPAYLOAD_DIGITCOUNT']._serialized_end=558
  _globals['_MIGRATIONPAYLOAD_OTPTYPE']._serialized_start=560
  _globals['_MIGRATIONPAYLOAD_OTPTYPE']._serialized_end=615
# @@protoc_insertion_point(module_scope)
